version: "3.9"
services:
  web:
    build: .
    ports:
      - "3333:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MayThe4th"
      ACCEPT_EULA: "Y"
