// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Data.Contexts;

namespace ProjectManagement.Data.Migrations
{
    [DbContext(typeof(DesignTimeProjectManagementContext))]
    [Migration("20200412183953_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagement.Data.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Code = "fc4c1eaa-576f-4fd8-ba70-e0adc1087271",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(2640),
                            Name = "proj 1",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 376, DateTimeKind.Local).AddTicks(3476),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 2,
                            Code = "af812c36-6d2e-456e-88bd-e7d7e209332b",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3388),
                            Name = "proj 2",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3370),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 3,
                            Code = "d37255b9-41b1-43e0-ae7c-31fac07a359c",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3462),
                            Name = "proj 3",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3458),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 4,
                            Code = "03645ae7-52bc-447f-b02c-afcd2c0ce805",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3472),
                            Name = "proj 4",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3470),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 5,
                            Code = "5d91de02-a8f0-4b72-b275-40629bc89fc5",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3481),
                            Name = "proj 5",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3478),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 6,
                            Code = "0e2f43fa-a001-4b67-a49c-53f8e78fcb28",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3499),
                            Name = "proj 6",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3497),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 7,
                            Code = "f176f4a6-6aef-4978-a1d4-e006a39baba8",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3508),
                            Name = "proj 7",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3505),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 8,
                            Code = "79f60518-b8d3-4620-b62e-9a208c15478f",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3516),
                            Name = "proj 8",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3514),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 9,
                            Code = "2fd02546-b3af-4b2b-b2ff-707ed02f1cf8",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3524),
                            Name = "proj 9",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3522),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 10,
                            Code = "29ccc235-5463-4330-bda3-023a124f6e40",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3534),
                            Name = "proj 10",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3531),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 11,
                            Code = "e1f6bb89-0cfa-40db-ba82-e4a17906eebe",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3542),
                            Name = "proj 11",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3540),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 12,
                            Code = "7edf9a4b-6b44-42ee-b46f-db1dee4ce35e",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3551),
                            Name = "proj 12",
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(3548),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 13,
                            Code = "7b4d3779-1127-4ee9-9223-1f5cdd428943",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4282),
                            Name = "proj 13 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4272),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 14,
                            Code = "292e6f33-2b14-4b4e-a597-37a0bba07626",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4731),
                            Name = "proj 14 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4722),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 15,
                            Code = "6386b167-5478-4370-aa1b-12e5696d54e2",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4751),
                            Name = "proj 15 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4748),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 16,
                            Code = "7d17a97f-8741-4164-8b6b-7e6f8f4b2311",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4761),
                            Name = "proj 16 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4759),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 17,
                            Code = "c447fdd9-47a0-4393-86bb-7fa64734ec29",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4772),
                            Name = "proj 17 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4769),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 18,
                            Code = "2dffa734-4e16-4443-8c6e-70a6a013c9cd",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4786),
                            Name = "proj 18 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4783),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 19,
                            Code = "c67a791e-3873-471b-bdf4-3c11cbf3c1fb",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4796),
                            Name = "proj 19 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4794),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 20,
                            Code = "0e9841bd-0609-402c-ad58-aa75faa6fa77",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4806),
                            Name = "proj 20 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4804),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 21,
                            Code = "bc47192d-6c24-48f2-b8af-87beb9ec2398",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4816),
                            Name = "proj 21 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(4814),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 22,
                            Code = "264357bb-4597-4c58-a8b6-ab11d86098d6",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(5444),
                            Name = "proj 22 with parent 18",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(5434),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 23,
                            Code = "b12f1efa-8e5d-4aec-824e-2f85dfa8a9c1",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(5552),
                            Name = "proj 23 with parent 18",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(5549),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectId = 24,
                            Code = "f17ca710-86b1-41f9-9e55-030040c097e0",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(5564),
                            Name = "proj 24 with parent 18",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 378, DateTimeKind.Local).AddTicks(5561),
                            State = "Planned"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Data.Entities.ProjectTask", b =>
                {
                    b.Property<int>("ProjectTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectTaskId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("ParentProjectTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            ProjectTaskId = 1,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(5215),
                            Name = "task 1 for project 1",
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(4833),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 2,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6148),
                            Name = "task 2 for project 2",
                            ProjectId = 2,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6131),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 3,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6170),
                            Name = "task 3 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6166),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 4,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6178),
                            Name = "task 4 for project 4",
                            ProjectId = 4,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6175),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 5,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6185),
                            Name = "task 5 for project 5",
                            ProjectId = 5,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6183),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 6,
                            Description = "some description for task 6",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6197),
                            Name = "task 6 for project 6",
                            ProjectId = 6,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6195),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 7,
                            Description = "some description for task 7",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6206),
                            Name = "task 7 for project 7",
                            ProjectId = 7,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6204),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 8,
                            Description = "some description for task 8",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6215),
                            Name = "task 8 for project 8",
                            ProjectId = 8,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6213),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 9,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6223),
                            Name = "task 9 for project 9",
                            ProjectId = 9,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6220),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 10,
                            Description = "some description for task 10",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6233),
                            Name = "task 10 for project 10",
                            ProjectId = 10,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6231),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 11,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6241),
                            Name = "task 11 for project 11",
                            ProjectId = 11,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6238),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 12,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6248),
                            Name = "task 12 for project 12",
                            ProjectId = 12,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6246),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 13,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6256),
                            Name = "task 13 for project 13",
                            ProjectId = 13,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6253),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 14,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6263),
                            Name = "task 14 for project 14",
                            ProjectId = 14,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6261),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 15,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6271),
                            Name = "task 15 for project 15",
                            ProjectId = 15,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6268),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 16,
                            Description = "some description for task 16",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6280),
                            Name = "task 16 for project 16",
                            ProjectId = 16,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6277),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 17,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6323),
                            Name = "task 17 for project 17",
                            ProjectId = 17,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6320),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 18,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6332),
                            Name = "task 18 for project 18",
                            ProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6330),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 19,
                            Description = "some description for task 19",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6342),
                            Name = "task 19 for project 19",
                            ProjectId = 19,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6339),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 20,
                            Description = "some description for task 20",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6351),
                            Name = "task 20 for project 20",
                            ProjectId = 20,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6348),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 21,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6358),
                            Name = "task 21 for project 21",
                            ProjectId = 21,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6356),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 22,
                            Description = "some description for task 22",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6367),
                            Name = "task 22 for project 22",
                            ProjectId = 22,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6365),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 23,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6375),
                            Name = "task 23 for project 23",
                            ProjectId = 23,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6372),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 24,
                            Description = "some description for task 24",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6384),
                            Name = "task 24 for project 24",
                            ProjectId = 24,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6381),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 25,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6894),
                            Name = "task 25 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6884),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 26,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6918),
                            Name = "task 26 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6915),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 27,
                            Description = "some description for task 27",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6928),
                            Name = "task 27 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6925),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 28,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6935),
                            Name = "task 28 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6933),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 29,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6943),
                            Name = "task 29 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6940),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 30,
                            Description = "some description for task 30",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6952),
                            Name = "task 30 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(6949),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 31,
                            Description = "some description for task 31",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(7523),
                            Name = "task 31 for project 1 with parent task 1",
                            ParentProjectTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(7513),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 32,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(7924),
                            Name = "task 32 for project 1 with parent task 1",
                            ParentProjectTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(7915),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 33,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(7945),
                            Name = "task 33 for project 1 with parent task 1",
                            ParentProjectTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(7942),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 34,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(8488),
                            Name = "task 34 for project 3 with parent task 3",
                            ParentProjectTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(8479),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 35,
                            Description = "some description for task 35",
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(8521),
                            Name = "task 35 for project 3 with parent task 3",
                            ParentProjectTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(8518),
                            State = "Planned"
                        },
                        new
                        {
                            ProjectTaskId = 36,
                            FinishDate = new DateTime(2020, 4, 15, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(8531),
                            Name = "task 36 for project 3 with parent task 3",
                            ParentProjectTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 21, 39, 53, 380, DateTimeKind.Local).AddTicks(8529),
                            State = "Planned"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Data.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagement.Data.Entities.Project", "ParentProject")
                        .WithMany("Projects")
                        .HasForeignKey("ParentProjectId");
                });

            modelBuilder.Entity("ProjectManagement.Data.Entities.ProjectTask", b =>
                {
                    b.HasOne("ProjectManagement.Data.Entities.ProjectTask", "ParentProjectTask")
                        .WithMany("Tasks")
                        .HasForeignKey("ParentProjectTaskId");

                    b.HasOne("ProjectManagement.Data.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
