// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Data.Contexts;

namespace ProjectManagement.Data.Migrations
{
    [DbContext(typeof(DesignTimeProjectManagementContext))]
    partial class DesignTimeProjectManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagement.Data.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Code = "dc45a0f2-d338-4679-9316-bb32c546e66a",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(870),
                            Name = "generated project 1",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 75, DateTimeKind.Local).AddTicks(1230),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 2,
                            Code = "d0f1595e-4058-4a8b-aa19-4dcf5588c260",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1860),
                            Name = "generated project 2",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1833),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 3,
                            Code = "0924499c-0e42-49cd-9761-719480cc73ca",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1887),
                            Name = "generated project 3",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1884),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 4,
                            Code = "67353727-5573-4364-8694-74c5e4115c30",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1893),
                            Name = "generated project 4",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1891),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 5,
                            Code = "d3a1bf3b-2bfb-4f35-8df4-2308932ae791",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1899),
                            Name = "generated project 5",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1897),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 6,
                            Code = "66763c95-aa06-4bbb-a57e-045339325e1a",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1906),
                            Name = "generated project 6",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1904),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 7,
                            Code = "7afbd710-d02e-4e51-abac-f26b6b0b8282",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1912),
                            Name = "generated project 7",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1910),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 8,
                            Code = "25367359-d07a-444f-8806-b426aec3c168",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1929),
                            Name = "generated project 8",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1927),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 9,
                            Code = "9c30f0cf-9764-4b2d-88a9-e43d07620093",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1936),
                            Name = "generated project 9",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1934),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 10,
                            Code = "50912d51-3592-4ef3-97ea-474dc4936bfa",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1942),
                            Name = "generated project 10",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1940),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 11,
                            Code = "9b1aa5af-cdbb-4411-bd22-7bc4c209ca9d",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1949),
                            Name = "generated project 11",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1946),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 12,
                            Code = "6b8a6885-1e6f-4c9c-8eaa-b3e1e5eb468a",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1955),
                            Name = "generated project 12",
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1953),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 13,
                            Code = "397ba183-29af-4538-bfcc-664d77c4bddb",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1962),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1959),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 14,
                            Code = "a13f5700-5448-41be-8cdf-0eeea5983ee4",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1969),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1966),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 15,
                            Code = "d9dc27bb-b46a-4e88-919b-35f7d331ab47",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1975),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1973),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 16,
                            Code = "879fcdf5-110b-4c6c-9655-ec9f1aa5bf9a",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1984),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1981),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 17,
                            Code = "063a42db-52a0-48a0-87e3-f790a53092bc",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1990),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1988),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 18,
                            Code = "4efd4e68-ae38-4fdd-922b-580f8f2e6764",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1997),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(1995),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 19,
                            Code = "1ff51c15-3711-429f-8cae-3ba8f9f677b9",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2003),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2001),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 20,
                            Code = "8c92244f-276d-42bf-b25f-87df40e6d4b2",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2010),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2007),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 21,
                            Code = "28efd369-c698-49fc-95fc-f01956e0210d",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2016),
                            Name = "nested project",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2014),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 22,
                            Code = "1f7c980a-ba4f-4f35-8103-e9d00d9765da",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2023),
                            Name = "nested project",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2020),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 23,
                            Code = "eaf26458-3960-4961-98ae-52a1ae62f12c",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2029),
                            Name = "nested project",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2027),
                            State = 0
                        },
                        new
                        {
                            ProjectId = 24,
                            Code = "420d6355-cbba-4314-8396-4924ee13d28a",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2037),
                            Name = "nested project",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 77, DateTimeKind.Local).AddTicks(2035),
                            State = 0
                        });
                });

            modelBuilder.Entity("ProjectManagement.Data.Entities.ProjectTask", b =>
                {
                    b.Property<int>("ProjectTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectTaskId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("ParentProjectTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            ProjectTaskId = 1,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3214),
                            Name = "task 1",
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(2810),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 2,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3625),
                            Name = "task 2",
                            ProjectId = 2,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3609),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 3,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3636),
                            Name = "task 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3634),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 4,
                            Description = "some description for task 4",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3988),
                            Name = "task 4",
                            ProjectId = 4,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(3980),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 5,
                            Description = "some description for task 5",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4007),
                            Name = "task 5",
                            ProjectId = 5,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4005),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 6,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4012),
                            Name = "task 6",
                            ProjectId = 6,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4010),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 7,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4017),
                            Name = "task 7",
                            ProjectId = 7,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4015),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 8,
                            Description = "some description for task 8",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4024),
                            Name = "task 8",
                            ProjectId = 8,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4022),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 9,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4029),
                            Name = "task 9",
                            ProjectId = 9,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4027),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 10,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4034),
                            Name = "task 10",
                            ProjectId = 10,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4032),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 11,
                            Description = "some description for task 11",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4041),
                            Name = "task 11",
                            ProjectId = 11,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4038),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 12,
                            Description = "some description for task 12",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4047),
                            Name = "task 12",
                            ProjectId = 12,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4045),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 13,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4052),
                            Name = "task 13",
                            ProjectId = 13,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4050),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 14,
                            Description = "some description for task 14",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4059),
                            Name = "task 14",
                            ProjectId = 14,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4056),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 15,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4064),
                            Name = "task 15",
                            ProjectId = 15,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4061),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 16,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4069),
                            Name = "task 16",
                            ProjectId = 16,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4066),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 17,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4074),
                            Name = "task 17",
                            ProjectId = 17,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4071),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 18,
                            Description = "some description for task 18",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4080),
                            Name = "task 18",
                            ProjectId = 18,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4078),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 19,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4085),
                            Name = "task 19",
                            ProjectId = 19,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4082),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 20,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4090),
                            Name = "task 20",
                            ProjectId = 20,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4087),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 21,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4094),
                            Name = "task 21",
                            ProjectId = 21,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4092),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 22,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4099),
                            Name = "task 22",
                            ProjectId = 22,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4097),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 23,
                            Description = "some description for task 23",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4105),
                            Name = "task 23",
                            ProjectId = 23,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4103),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 24,
                            Description = "some description for task 24",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4112),
                            Name = "task 24",
                            ProjectId = 24,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4110),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 25,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4117),
                            Name = "task 25",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4115),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 26,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4122),
                            Name = "task 26",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4119),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 27,
                            Description = "some description for task 27",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4128),
                            Name = "task 27",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4126),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 28,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4133),
                            Name = "task 28",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4130),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 29,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4137),
                            Name = "task 29",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4135),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 30,
                            Description = "some description for task 30",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4144),
                            Name = "task 30",
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4142),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 31,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4149),
                            Name = "task 31",
                            ParentProjectTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4147),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 32,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4154),
                            Name = "task 32",
                            ParentProjectTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4151),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 33,
                            Description = "some description for task 33",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4160),
                            Name = "task 33",
                            ParentProjectTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4158),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 34,
                            Description = "some description for task 34",
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4166),
                            Name = "task 34",
                            ParentProjectTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4164),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 35,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4171),
                            Name = "task 35",
                            ParentProjectTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4169),
                            State = 0
                        },
                        new
                        {
                            ProjectTaskId = 36,
                            FinishDate = new DateTime(2020, 4, 15, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4176),
                            Name = "task 36",
                            ParentProjectTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2020, 4, 12, 14, 28, 3, 79, DateTimeKind.Local).AddTicks(4174),
                            State = 0
                        });
                });

            modelBuilder.Entity("ProjectManagement.Data.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagement.Data.Entities.Project", "ParentProject")
                        .WithMany("Projects")
                        .HasForeignKey("ParentProjectId");
                });

            modelBuilder.Entity("ProjectManagement.Data.Entities.ProjectTask", b =>
                {
                    b.HasOne("ProjectManagement.Data.Entities.ProjectTask", "ParentProjectTask")
                        .WithMany("Tasks")
                        .HasForeignKey("ParentProjectTaskId");

                    b.HasOne("ProjectManagement.Data.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
