// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Api.Data;

namespace ProjectManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210906200454_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("Projects", "system");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "43e19839-3e73-4c29-a930-60e4152e8f02",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(1715),
                            Name = "proj 1",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 949, DateTimeKind.Local).AddTicks(783),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "0d372061-38d2-4a97-b10d-4b39ba1802f5",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2349),
                            Name = "proj 2",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2331),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "511fa3e2-1c25-43ec-b7ab-c247d02f0ae6",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2436),
                            Name = "proj 3",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2432),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "50c554e8-021a-40b6-b5d0-fed9ab1debb1",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2487),
                            Name = "proj 4",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2485),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "2a71e482-2b01-433d-9591-bfd514e0866d",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2497),
                            Name = "proj 5",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2494),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "8330cf4c-84c5-4dbc-9f16-635c91bfc61c",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2508),
                            Name = "proj 6",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2506),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "3bdddefd-6ab2-4ea7-8abd-435ba1719fc2",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2517),
                            Name = "proj 7",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2515),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "4a7d3a08-6b74-4274-80b6-cbeef852630a",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2525),
                            Name = "proj 8",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2523),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "f62b6d43-f962-4b04-81bd-e5f0e1ddf33b",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2540),
                            Name = "proj 9",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2537),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "5aba5cf0-6b48-441d-8ec2-eced0ce30293",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2550),
                            Name = "proj 10",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2547),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "064d451b-5481-4525-9e4e-034db032592e",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2558),
                            Name = "proj 11",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2556),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "b26cd88b-d0af-4a72-a17b-b4ed7ca0b6ce",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2566),
                            Name = "proj 12",
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(2564),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "7dff24d4-b5bd-4497-bd7a-883022c4084c",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3152),
                            Name = "proj 13 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3142),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "98914423-77a8-487c-be2a-c5f5881c6665",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3450),
                            Name = "proj 14 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3442),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "c0733f10-5983-49b6-8b3a-c8c05abdf9d6",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3470),
                            Name = "proj 15 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3467),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "a98a93ca-2f6b-423d-bb7e-f3b4a1bb8085",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3481),
                            Name = "proj 16 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3478),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "f1dc6e4d-6b95-4333-801e-cd292eadb4d7",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3496),
                            Name = "proj 17 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3493),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "b3058ab9-89e0-4416-a424-471253b5522e",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3509),
                            Name = "proj 18 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3507),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "4e4d3d12-453a-45dc-824c-99624cb3c4cf",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3520),
                            Name = "proj 19 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3518),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "e460c64e-75f1-42c9-a9f3-6859b40910ca",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3531),
                            Name = "proj 20 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3528),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "963b568c-e212-4c86-8006-c2820bef7efb",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3541),
                            Name = "proj 21 with parent 3",
                            ParentProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(3539),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "a3dea03c-cfe5-4377-a328-003cba08b59f",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(4039),
                            Name = "proj 22 with parent 18",
                            ParentProjectId = 18L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(4030),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "d9fc3027-5a2c-425e-ba25-8f70081ac9b8",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(4070),
                            Name = "proj 23 with parent 18",
                            ParentProjectId = 18L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(4066),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "db2cf9e6-9512-4f51-bd17-116ffb4fb8fe",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(4082),
                            Name = "proj 24 with parent 18",
                            ParentProjectId = 18L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 951, DateTimeKind.Local).AddTicks(4079),
                            State = "Planned"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.ProjectTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks", "system");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "some description for task 1",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(342),
                            Name = "task 1 for project 1",
                            ProjectId = 1L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(71),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "some description for task 2",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1019),
                            Name = "task 2 for project 2",
                            ProjectId = 2L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1003),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "some description for task 3",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1043),
                            Name = "task 3 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1040),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "some description for task 4",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1052),
                            Name = "task 4 for project 4",
                            ProjectId = 4L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1049),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "some description for task 5",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1060),
                            Name = "task 5 for project 5",
                            ProjectId = 5L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1058),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "some description for task 6",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1071),
                            Name = "task 6 for project 6",
                            ProjectId = 6L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1068),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 7L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1078),
                            Name = "task 7 for project 7",
                            ProjectId = 7L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1076),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 8L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1085),
                            Name = "task 8 for project 8",
                            ProjectId = 8L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1083),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 9L,
                            Description = "some description for task 9",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1093),
                            Name = "task 9 for project 9",
                            ProjectId = 9L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1091),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 10L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1102),
                            Name = "task 10 for project 10",
                            ProjectId = 10L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1099),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 11L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1109),
                            Name = "task 11 for project 11",
                            ProjectId = 11L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1107),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 12L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1115),
                            Name = "task 12 for project 12",
                            ProjectId = 12L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1113),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 13L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1122),
                            Name = "task 13 for project 13",
                            ProjectId = 13L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1120),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 14L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1129),
                            Name = "task 14 for project 14",
                            ProjectId = 14L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1127),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 15L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1179),
                            Name = "task 15 for project 15",
                            ProjectId = 15L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1176),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 16L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1187),
                            Name = "task 16 for project 16",
                            ProjectId = 16L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1185),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 17L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1194),
                            Name = "task 17 for project 17",
                            ProjectId = 17L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1192),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 18L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1202),
                            Name = "task 18 for project 18",
                            ProjectId = 18L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1200),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 19L,
                            Description = "some description for task 19",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1211),
                            Name = "task 19 for project 19",
                            ProjectId = 19L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1208),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 20L,
                            Description = "some description for task 20",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1219),
                            Name = "task 20 for project 20",
                            ProjectId = 20L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1217),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 21L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1226),
                            Name = "task 21 for project 21",
                            ProjectId = 21L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1224),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 22L,
                            Description = "some description for task 22",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1234),
                            Name = "task 22 for project 22",
                            ProjectId = 22L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1232),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 23L,
                            Description = "some description for task 23",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1243),
                            Name = "task 23 for project 23",
                            ProjectId = 23L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1240),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 24L,
                            Description = "some description for task 24",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1251),
                            Name = "task 24 for project 24",
                            ProjectId = 24L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1249),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 25L,
                            Description = "some description for task 25",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1632),
                            Name = "task 25 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1623),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 26L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1655),
                            Name = "task 26 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1652),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 27L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1663),
                            Name = "task 27 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1661),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 28L,
                            Description = "some description for task 28",
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1672),
                            Name = "task 28 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1670),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 29L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1679),
                            Name = "task 29 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1677),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 30L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1687),
                            Name = "task 30 for project 3",
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(1685),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 31L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2100),
                            Name = "task 31 for project 1 with parent task 1",
                            ParentTaskId = 1L,
                            ProjectId = 1L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2090),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 32L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2352),
                            Name = "task 32 for project 1 with parent task 1",
                            ParentTaskId = 1L,
                            ProjectId = 1L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2344),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 33L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2370),
                            Name = "task 33 for project 1 with parent task 1",
                            ParentTaskId = 1L,
                            ProjectId = 1L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2368),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 34L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2758),
                            Name = "task 34 for project 3 with parent task 3",
                            ParentTaskId = 3L,
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2749),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 35L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2788),
                            Name = "task 35 for project 3 with parent task 3",
                            ParentTaskId = 3L,
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2785),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 36L,
                            FinishDate = new DateTime(2021, 9, 9, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2799),
                            Name = "task 36 for project 3 with parent task 3",
                            ParentTaskId = 3L,
                            ProjectId = 3L,
                            StartDate = new DateTime(2021, 9, 6, 23, 4, 53, 953, DateTimeKind.Local).AddTicks(2796),
                            State = "Planned"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagement.Api.Data.Entities.Project", "ParentProject")
                        .WithMany("Projects")
                        .HasForeignKey("ParentProjectId");

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.ProjectTask", b =>
                {
                    b.HasOne("ProjectManagement.Api.Data.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
