// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Api.Data;

namespace ProjectManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210905215253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "114d17ed-4bde-478a-a978-ba917d2cf942",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(5340),
                            Name = "proj 1",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 368, DateTimeKind.Local).AddTicks(4630),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Code = "a11bce64-23b0-435a-98c2-d44eef6cc905",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6510),
                            Name = "proj 2",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6490),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 3,
                            Code = "5564c612-7da9-40c4-808a-3fb57e1d6c23",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6640),
                            Name = "proj 3",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6640),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 4,
                            Code = "df3eabe7-3d01-46f6-8b00-6231854813c3",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6660),
                            Name = "proj 4",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6650),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 5,
                            Code = "2edc45f4-988d-4123-a5a3-0a33396f0356",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6670),
                            Name = "proj 5",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6660),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 6,
                            Code = "b2fc6aca-30f1-4516-ba22-a8863921dff9",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6680),
                            Name = "proj 6",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6680),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 7,
                            Code = "2af1fdbd-6a2d-4705-af35-25cc746d8468",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6690),
                            Name = "proj 7",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6690),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 8,
                            Code = "be5cec30-e510-4a62-895e-ece9fbcfab6e",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6710),
                            Name = "proj 8",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6700),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 9,
                            Code = "1b682342-5646-4846-a516-0d33e9dca756",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6720),
                            Name = "proj 9",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6710),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 10,
                            Code = "51fec66d-e0e3-4f7f-9bec-d2a8447794e0",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6730),
                            Name = "proj 10",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6730),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 11,
                            Code = "b965af40-c2e9-406f-9f63-d3de42a02d17",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6740),
                            Name = "proj 11",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6740),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 12,
                            Code = "cf6a2ac9-9725-492d-b3af-d73d2f35ae3b",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6750),
                            Name = "proj 12",
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(6750),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 13,
                            Code = "3b09d51f-f0a4-49ec-8b32-35f32856bcb4",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(7820),
                            Name = "proj 13 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(7800),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 14,
                            Code = "0a1cc6b2-7244-401a-aef1-213049f4fcd5",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8470),
                            Name = "proj 14 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8450),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 15,
                            Code = "d10212a4-3633-4298-a7c9-9a12d38cc992",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8600),
                            Name = "proj 15 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8590),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 16,
                            Code = "702297c6-c451-471f-8c16-d075f1a9b941",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8610),
                            Name = "proj 16 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8610),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 17,
                            Code = "047a2898-2e69-465c-9ff8-1330b69f0252",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8630),
                            Name = "proj 17 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8620),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 18,
                            Code = "657a996f-390a-43cc-9c5b-10964386446c",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8640),
                            Name = "proj 18 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8640),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 19,
                            Code = "071fa488-465c-4194-8b10-281d9f30445d",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8660),
                            Name = "proj 19 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8650),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 20,
                            Code = "fa72ca95-3043-4be3-ae34-2356b33e1028",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8670),
                            Name = "proj 20 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8670),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 21,
                            Code = "fa42b22c-faf3-43f2-977a-9b09113ad949",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8680),
                            Name = "proj 21 with parent 3",
                            ParentProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(8680),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 22,
                            Code = "e0e22f58-347a-4054-9674-b675113c7321",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(9470),
                            Name = "proj 22 with parent 18",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(9460),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 23,
                            Code = "144501aa-fe24-4af1-8e5a-d465f6a54c4f",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(9510),
                            Name = "proj 23 with parent 18",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(9510),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 24,
                            Code = "762e6417-671d-4898-8f37-311cad7d6a90",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(9520),
                            Name = "proj 24 with parent 18",
                            ParentProjectId = 18,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 376, DateTimeKind.Local).AddTicks(9520),
                            State = "Planned"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(8420),
                            Name = "task 1 for project 1",
                            ProjectId = 1,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(7940),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9700),
                            Name = "task 2 for project 2",
                            ProjectId = 2,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9680),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 3,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9730),
                            Name = "task 3 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9720),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 4,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9740),
                            Name = "task 4 for project 4",
                            ProjectId = 4,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9730),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 5,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9750),
                            Name = "task 5 for project 5",
                            ProjectId = 5,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9740),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 6,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9760),
                            Name = "task 6 for project 6",
                            ProjectId = 6,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9760),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 7,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9770),
                            Name = "task 7 for project 7",
                            ProjectId = 7,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9770),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 8,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9780),
                            Name = "task 8 for project 8",
                            ProjectId = 8,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9780),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 9,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9790),
                            Name = "task 9 for project 9",
                            ProjectId = 9,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9780),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 10,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9800),
                            Name = "task 10 for project 10",
                            ProjectId = 10,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9800),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 11,
                            Description = "some description for task 11",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9810),
                            Name = "task 11 for project 11",
                            ProjectId = 11,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9810),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 12,
                            Description = "some description for task 12",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9820),
                            Name = "task 12 for project 12",
                            ProjectId = 12,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9820),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 13,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9830),
                            Name = "task 13 for project 13",
                            ProjectId = 13,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9830),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 14,
                            Description = "some description for task 14",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9840),
                            Name = "task 14 for project 14",
                            ProjectId = 14,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9840),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 15,
                            Description = "some description for task 15",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9850),
                            Name = "task 15 for project 15",
                            ProjectId = 15,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9850),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 16,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9860),
                            Name = "task 16 for project 16",
                            ProjectId = 16,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9860),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 17,
                            Description = "some description for task 17",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9880),
                            Name = "task 17 for project 17",
                            ProjectId = 17,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9870),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 18,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9890),
                            Name = "task 18 for project 18",
                            ProjectId = 18,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9880),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 19,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9890),
                            Name = "task 19 for project 19",
                            ProjectId = 19,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9890),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 20,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9900),
                            Name = "task 20 for project 20",
                            ProjectId = 20,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9900),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 21,
                            Description = "some description for task 21",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9910),
                            Name = "task 21 for project 21",
                            ProjectId = 21,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9910),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 22,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9920),
                            Name = "task 22 for project 22",
                            ProjectId = 22,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9920),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 23,
                            Description = "some description for task 23",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9930),
                            Name = "task 23 for project 23",
                            ProjectId = 23,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9930),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 24,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9940),
                            Name = "task 24 for project 24",
                            ProjectId = 24,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 379, DateTimeKind.Local).AddTicks(9940),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 25,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(540),
                            Name = "task 25 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(520),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 26,
                            Description = "some description for task 26",
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(570),
                            Name = "task 26 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(570),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 27,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(580),
                            Name = "task 27 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(580),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 28,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(590),
                            Name = "task 28 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(590),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 29,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(600),
                            Name = "task 29 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(600),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 30,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(610),
                            Name = "task 30 for project 3",
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(610),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 31,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(1320),
                            Name = "task 31 for project 1 with parent task 1",
                            ParentTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(1310),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 32,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(1920),
                            Name = "task 32 for project 1 with parent task 1",
                            ParentTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(1910),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 33,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2000),
                            Name = "task 33 for project 1 with parent task 1",
                            ParentTaskId = 1,
                            ProjectId = 1,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2000),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 34,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2700),
                            Name = "task 34 for project 3 with parent task 3",
                            ParentTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2690),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 35,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2740),
                            Name = "task 35 for project 3 with parent task 3",
                            ParentTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2740),
                            State = "Planned"
                        },
                        new
                        {
                            Id = 36,
                            FinishDate = new DateTime(2021, 9, 9, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2760),
                            Name = "task 36 for project 3 with parent task 3",
                            ParentTaskId = 3,
                            ProjectId = 3,
                            StartDate = new DateTime(2021, 9, 6, 0, 52, 53, 380, DateTimeKind.Local).AddTicks(2760),
                            State = "Planned"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagement.Api.Data.Entities.Project", "ParentProject")
                        .WithMany("Projects")
                        .HasForeignKey("ParentProjectId");

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.ProjectTask", b =>
                {
                    b.HasOne("ProjectManagement.Api.Data.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagement.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
